### ISSUE TITLE
ALB log: ValueError: dict contains fields not in fieldnames: 'geo_city'

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#126]
### Describe the bug

When I create an ALB log ingestion pipeline, the `LogProcessorFn` lambda will show the error message. 

```
[INFO]	2023-05-04T02:52:19.006Z	f8db5eae-3aed-5f68-aa21-02631af441d6	Export failed records to xxxxx
[8:42 PM] [ERROR] ValueError: dict contains fields not in fieldnames: 'geo_city'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 102, in lambda_handler
    status_code = export_failed_records(
  File "/var/task/lambda_function.py", line 150, in export_failed_records
    body = write_to_csv(failed_records)
  File "/var/task/lambda_function.py", line 130, in write_to_csv
    writer.writerow(record)
  File "/var/lang/lib/python3.9/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/var/lang/lib/python3.9/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
```

### Expected Behavior

The logs can be exported to S3, if not being ingested into OpenSearch correctly.

### Current Behavior

Data not exported to S3, and error message in CloudWatch Logs.

### Solution Version

v1.0.1

### AWS Region. e.g., us-east-1

us-east-1

**Comment by JoeShi** [comment]
**Root Cause**
The log pipeline used MaxMind database to convert and IP address into Geo location. In some corner cases, the MaxMind database did not return `geo_city` information. 

**Quick Fix**
1. Find the Lambda provisioned by this solution, and the Lambda name should contains `LogProcessorFn`.
2. Open the `lambda_function.py` on the AWS Lambda console.
3. Find the line `fieldnames = json_records[0].keys()`. It should be around line 126.
4. Replace with the following code
```
fieldnames = set(json_records[0].keys()) | {
        "geo_iso_code",
        "geo_location",
        "geo_country",
        "geo_city",
}
```

**Mitigation plan**
We will fix this issue in next release.

**Comment by JoeShi** [comment]
fixed in v2 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.0.0
